export const productListing = [
    {
    id : 1,
    name : "Extra Soft Touch Lamb Doll",
    category:"Toys",
    des :"Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes : "Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 8,
    image :"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-12.jpg", 
    qty:1,
   },
    {
    id : 2,
    name : "Teddy Bear Ready To Flight Doll",
    category:"Toys",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes : "Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 10,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-7.jpg",
    qty:1,
   },
    {
    id : 3,
    name : "ZooMate 3 Animal Set Toys",
    category:"Toys",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 12,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-4.jpg",
    qty:1,
   },
    {
    id : 4,
    name : "Twin Cute Bunny Set Combo",
    category:"cloths",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 40.25,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-11.jpg",
    qty:1,
   },
    {
    id : 5,
    name : "Colorful Birdies on Orange Bandana",
    category:"cloths",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 4.75,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-10.jpg",
    qty:1,
   },
    
    {
    id : 7,
    name : "Sunny Outdoor Picnic Set Yellow",
    category:"cloths",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 35.50 ,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-8.jpg",
    qty:1,
   },
    {
    id : 8,
    name : "Cute Brown Sheep Sleeveless",
    category:"cloths",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 30.50,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-3.jpg",
    qty:1,
   } ,
    {
    id : 9,
    name : "Nutrikids Food Nutrition DHA+ Orange",
    category:"nutrition",
    des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
    deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
    rate : 6.50 ,
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-9.jpg",
    qty:1,
   },
   {
   id : 10,
   name : "VitCom Nutrition Fruits Flavor",
   category:"nutrition",
   des : "Pellentesque nisl ac dictum tincidunt ut viverra non, sem in sed fringilla a quis eu in et, aliquet convallis ornare pellentesque nibh phasellus tempor.",
   deepdes :"Egestas fringilla eu pellentesque phasellus sed varius non ut tincidunt sed massa nec massa pulvinar ipsum sed vitae vitae feugiat sem in etiam non turpis blandit lorem fringilla lacus elementum urna maecenas proin eget fermentum nunc morbi mus pretium cursus",
   rate : 9 ,
   image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-6.jpg",
   qty:1,
  },
]